import time
import pyautogui



pyautogui.click(x=-935, y=408)
time.sleep(1)
pyautogui.write("2")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("625")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("6")
pyautogui.hotkey("enter")
time.sleep(15)
pyautogui.hotkey("enter")
pyautogui.click(x=-935, y=408)
time.sleep(1)
pyautogui.write("2")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("1346")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("2")
pyautogui.hotkey("enter")
time.sleep(15)
pyautogui.hotkey("enter")
pyautogui.click(x=-935, y=408)
time.sleep(1)
pyautogui.write("2")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("1349")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("2")
pyautogui.hotkey("enter")
time.sleep(15)
pyautogui.hotkey("enter")
pyautogui.click(x=-935, y=408)
time.sleep(1)
pyautogui.write("2")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("966")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("3")
pyautogui.hotkey("enter")
time.sleep(15)
pyautogui.hotkey("enter")
pyautogui.click(x=-935, y=408)
time.sleep(1)
pyautogui.write("2")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("1303")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("3")
pyautogui.hotkey("enter")
time.sleep(15)
pyautogui.hotkey("enter")
pyautogui.click(x=-935, y=408)
time.sleep(1)
pyautogui.write("2")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("776")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("6")
pyautogui.hotkey("enter")
time.sleep(15)
pyautogui.hotkey("enter")
pyautogui.click(x=-935, y=408)
time.sleep(1)
pyautogui.write("2")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("655")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("5")
pyautogui.hotkey("enter")
time.sleep(15)